root: true
extends:
  - 'next/core-web-vitals'
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:unicorn/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
plugins:
  - drizzle
  - '@typescript-eslint'
  - eslint-plugin-no-cyrillic-string
rules:
  '@typescript-eslint/consistent-type-imports':
    - error
    - disallowTypeAnnotations: false
      fixStyle: separate-type-imports
  'drizzle/enforce-delete-with-where': 'error'
  'drizzle/enforce-update-with-where': 'error'
  'unicorn/explicit-length-check': 'off'
  'unicorn/filename-case': 'off'
  'unicorn/prefer-module': 'off'
  'unicorn/no-array-reduce': 'off'
  '@typescript-eslint/no-unused-vars': 'warn'
  'unicorn/prevent-abbreviations': 'warn'
  'unicorn/consistent-function-scoping': 'off'
  'unicorn/no-null': 'off'
  'unicorn/prefer-top-level-await': 'off'
  'unicorn/no-process-exit': 'off'
  'unicorn/no-array-for-each': 'off'
  '@typescript-eslint/no-non-null-asserted-optional-chain': 'warn'
  '@typescript-eslint/no-explicit-any': 'warn'
  '@typescript-eslint/ban-ts-comment': 'off'
